### ISSUE TITLE
MQQT Discovery for climate, need quotes

### ISSUE THREAD

**Issue by klim123123** [hassio-addons/addon-zwavejs2mqtt#241]
# Problem/Motivation

There is a bug when you enable MQQT Discovery and you have thermostat connected to zwavejs2mqtt.
HA can't properly detect thermostat mode status, because of the error in config created by zwavejs2mqtt.

![image](https://user-images.githubusercontent.com/64870895/130137498-7019b15e-0678-4e7a-adff-e4d1ab94622c.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/64870895/130137875-6710e4af-13e3-4f88-ab6e-41184774ff0a.png)

## Actual behavior
Thermostat mode is not detecting correctly:
![image](https://user-images.githubusercontent.com/64870895/130137698-d6812243-beab-41da-8ec5-7add9669c7c0.png)

## Steps to reproduce

Add thermostat to zwavejs2mqtt and enable MQQT Discovery.

## Proposed changes
in config created by zwavejs2mqtt i found:
"mode_state_template": "{{ {0: \"off\", 1: \"heat\"}[value] | default('off') }}",

it's should be:
mode_state_template: '{{ {"0": "off", "1": "heat"}[value] | default(''off'') }}'
(need to add quotes near 0 and 1)

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is an issue with the Z-Wave JS to MQTT software which this project wraps. (Add-ons wrap existing software).

Please report this issue upstream.

Additionally, I would highly recommend using the Z-Wave JS integration in Home Assistant instead of MQTT to connect your Z-Wave JS and Home Assistant instances together.
