### ISSUE TITLE
Yale Real Living deadbolt does not send alerts

### ISSUE THREAD

**Issue by Adam-Langley** [hassio-addons/addon-zwavejs2mqtt#369]
# Problem/Motivation

I have joined a YRL220 deadbolt to my zwavejs2mqtt network, manual turning of the deadbolt, or the "timed autolock" do not result in the locked state changing in HA - hence the software and hardware "locked" state dont agree.

## Expected behavior

If manually locking or unlocking the door, or the door auto-locks, an alert should be sent to the Zwave controller which then updates the "locked" state of the entity in Home Assistant.

## Actual behavior

No notifications are sent/received.
The correct state is read, however, if I force zwavejs2mqtt to re-read all attributes.

## Steps to reproduce

Raspbery Pi 4, with Home Assistant OS.
Zwavejs2mqtt
Aeotect Z-Stick Gen5+
Yale YRL220 deadbolt

## Proposed changes

I don't know mych about zwave, however I expect that zwave devices expect an "alert subscription" to be requested by the controller (for the sake of keeping network chatter to a minimum). Maybe this is not being done? I dont see anything in zwavejsmqtt that would allow me o manually set this up, like in zigbee2mqtt/

Device debug json attached.

[yrd220debug.json.zip](https://github.com/hassio-addons/addon-zwavejs2mqtt/files/8644209/yrd220debug.json.zip)

**Comment by frenck** [comment]
Hi there @Adam-Langley 👋 

Thanks for reporting an issue, however, your issue is not specific to the add-on. Add-ons wrap existing applications and do not build/create those applications themselves.

Your issue is with the application running inside the containers. In this case, I would recommend you raising this issue with the Home Assistant Core project as a starting point:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
