### ISSUE TITLE
All Fibaro Door window sensors FGK101 become unavailable after last update

### ISSUE THREAD

**Issue by anonymous66va** [hassio-addons/addon-zwavejs2mqtt#387]
![ScreenHunter 408](https://user-images.githubusercontent.com/85165779/174430992-f1f1b54d-8f73-4f44-a806-b382389cb035.jpg)
# Problem/Motivation

> FgK101 no longer work. They were perfect before the last update.

## Expected behavior

>This is clearly a bug. I expect everything to work as it did before the latest release.

## Actual behavior

> I have many nodes but only FGK101 stuck during the interview process.
I've tried everything :
wakeup / exclude & reinclude , but nothing , the behavior is always the same (the interview stucks in an infinite loop).
Please avoid suggesting any actions described above. I have tried everything and more.

## Steps to reproduce

> Update the software at the last release.

## Proposed changes
It would be much appreciated an option to abort the interview procedure.

**Comment by frenck** [comment]
Add-ons wrap existing software, in this case: `zwavejs2mqtt`.

This issue has not a root cause in the add-on itself, but in `zwavejs2mqtt` itself (or one of its dependencies.

Please report your issue with the upstream project here: <https://github.com/zwave-js/zwavejs2mqtt>

Once it is solved and released an in update upstream, the add-on will follow the upstream update.
